import { t } from '../data/i18n.js';
import { site } from '../data/site.js';
import { services, industries, experts, pages, legalPages } from '../data/content.js';

const path = window.location.pathname.replace(/\/+$/, '') || '/';
const lang = path.startsWith('/en') ? 'en' : 'fr';
const tr = t[lang];
const prefix = `/${lang}`;
const isRoot = path === '/' || path === '/fr' || path === '/en';
const isAdmin = path === '/admin' || path === '/admin/login';

const esc = s => String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pathFor = slug => `${prefix}${slug ? `/${slug}` : '/'}`;
const nav = [
  ['about',pages.about],['services',tr.services],['projects',pages.projects],['insights',pages.insights],['actuality',pages.actuality],['sustainability',pages.sustainability],['experts',pages.experts],['careers',pages.careers],['contact',pages.contact]
];

const siteIndex = [
  {title:tr.home,url:pathFor(''),desc:tr.hero},
  ...nav.map(([key,label]) => ({title: typeof label==='string'?label:label[lang], url:pathFor(key==='services'?'services-industries':key==='about'?'about':key), desc:label[lang] || label}))
];

function header(){
  const links = nav.map(([key,label])=>{
    const href=key==='services'?pathFor('services-industries'):pathFor(key);
    const current=path===href?' aria-current="page"':'';
    return `<li><a class="nav-link" href="${href}"${current}>${esc(typeof label==='string'?label:label[lang])}</a></li>`;
  }).join('');
  return `<header class="site-header" id="site-header"><div class="header-inner">
    <a class="logo-link" href="${prefix}/" aria-label="Africa Power Advisory Holding, ${tr.home}"><img class="logo-dark" src="/assets/brand/apah-logo.svg" width="190" height="48" alt="Africa Power Advisory Holding"><img class="logo-light" src="/assets/brand/apah-logo-light.svg" width="190" height="48" alt="Africa Power Advisory Holding"></a>
    <nav class="desktop-nav" aria-label="Primary navigation"><ul class="nav-list">${links}</ul></nav>
    <div class="utility"><button class="utility-btn" id="search-open" type="button" aria-haspopup="dialog">${tr.search}</button><button class="utility-btn desktop-only" id="theme-toggle" type="button">${tr.dark}</button><a class="cta desktop-only" href="${pathFor('contact')}">${tr.contact}</a><button class="menu-button" id="menu-open" type="button" aria-expanded="false" aria-controls="mobile-panel" aria-label="${tr.openMenu}">☰</button></div>
  </div></header>
  <aside class="mobile-panel" id="mobile-panel" data-open="false" aria-hidden="true"><div class="mobile-top"><img src="/assets/brand/apah-logo-light.svg" width="180" height="46" alt="Africa Power Advisory Holding"><button class="menu-button" id="menu-close" type="button" aria-label="${tr.closeMenu}">×</button></div><nav class="mobile-nav" aria-label="${tr.menu}">${links}</nav><div class="mobile-utility"><button class="utility-btn" id="mobile-theme-toggle" type="button">${tr.dark}</button><button class="utility-btn" id="mobile-search-open" type="button">${tr.search}</button><a class="cta" href="${pathFor('contact')}">${tr.contact}</a><div class="language-switch"><a href="/fr/" lang="fr" ${lang==='fr'?'aria-current="true"':''}>Français</a><a href="/en/" lang="en" ${lang==='en'?'aria-current="true"':''}>English</a></div></div></aside>`;
}

function footer(){
  return `<footer class="site-footer"><div class="footer-inner"><div class="footer-grid">
    <section><img class="footer-logo" src="/assets/brand/apah-logo-light.svg" width="230" height="58" alt="Africa Power Advisory Holding"><h2 class="footer-title">${tr.offices}</h2><ul class="footer-links office-list">${site.company.offices.map(o=>`<li>${esc(o[lang])}</li>`).join('')}</ul><p>${tr.socialPending}</p><div class="social-slot" aria-label="Social media status">${tr.socialPending}</div></section>
    <section><div class="footer-title">${tr.about}</div><ul class="footer-links"><li><a href="${pathFor('about')}">${tr.about}</a></li><li><a href="${pathFor('experts')}">${tr.experts}</a></li><li><a href="${pathFor('careers')}">${tr.careers}</a></li><li><a href="${pathFor('actuality')}">${tr.actuality}</a></li><li><a href="${pathFor('contact')}">${tr.contact}</a></li></ul></section>
    <section><div class="footer-title">${tr.legal}</div><ul class="footer-links">${Object.entries(legalPages).map(([key,v])=>`<li><a href="${pathFor(`legal/${key}`)}">${esc(v[lang])}</a></li>`).join('')}</ul><div class="language-switch"><a href="/fr/" lang="fr" ${lang==='fr'?'aria-current="true"':''}>Français</a><a href="/en/" lang="en" ${lang==='en'?'aria-current="true"':''}>English</a></div></section>
  </div><div class="footer-bottom"><span>© <span data-year></span> Africa Power Advisory Holding. ${tr.rights}</span><a href="${pathFor('newsletter')}">${tr.newsletter}</a></div></div></footer>`;
}

function dialog(){ return `<dialog class="search-dialog" id="site-search" aria-labelledby="search-title"><div class="dialog-inner"><div class="dialog-top"><h2 id="search-title">${tr.searchSite}</h2><button class="utility-btn" id="search-close" type="button" aria-label="${tr.closeMenu}">×</button></div><p>${tr.searchHint}</p><label class="sr-only" for="search-input">${tr.searchPlaceholder}</label><input class="search-input" id="search-input" type="search" placeholder="${tr.searchPlaceholder}" autocomplete="off"><div class="search-results" id="search-results" aria-live="polite"></div></div></dialog>`; }

function hero(title, intro=''){ return `<section class="page-hero"><div><span class="eyebrow">Africa Power Advisory Holding</span><h1>${esc(title)}</h1>${intro?`<p>${esc(intro)}</p>`:''}</div></section>`; }
function card(title,desc,href){ return `<article class="card"><h3>${esc(title)}</h3><p>${esc(desc)}</p>${href?`<a class="text-link" href="${href}">${tr.readMore}</a>`:''}</article>`; }

function home(){
  return `<main id="main-content"><section class="hero"><div class="hero-content"><span class="eyebrow">Africa Power Advisory Holding</span><h1>${tr.hero}</h1><p>${tr.heroText}</p><div class="hero-actions"><a class="cta" href="${pathFor('contact')}">${tr.discuss}</a><a class="cta secondary" href="${pathFor('contact')}">${tr.advisory}</a><a class="cta secondary" href="${pathFor('contact')}">${tr.speak}</a></div></div></section><section class="accent-band"><div class="band-inner"><p>${tr.heroText}</p><div class="band-actions"><a class="cta" href="${pathFor('services-industries')}">${tr.services}</a></div></div></section>
  <section class="section"><div class="section-header"><span class="eyebrow">${tr.what}</span><h2>${tr.services}</h2><p>${lang==='fr'?'Conseil énergétique, systèmes électriques, projets, approvisionnement, efficacité, transition, réglementation et intelligence énergétique.': 'Energy advisory, power systems, projects, procurement, efficiency, transition, regulation and energy intelligence.'}</p></div><div class="card-grid">${services.slice(0,6).map(s=>card(lang==='fr'?s.fr:s.en,s.desc,`${pathFor('services-industries/services')}/${s.slug}`)).join('')}</div></section>
  <section class="section section-dark"><div class="section-header"><span class="eyebrow">${tr.who}</span><h2>${tr.who}</h2><p>${lang==='fr'?'Secteurs servis selon les informations fournies.':'Sectors served based on supplied company information.'}</p></div><div class="card-grid">${industries.slice(0,6).map(i=>card(lang==='fr'?i.fr:i.en,lang==='fr'?'Secteur cible':'Target sector',`${pathFor('services-industries/industries')}/${i.slug}`)).join('')}</div></section>
  <section class="section"><div class="section-header"><span class="eyebrow">${tr.experts}</span><h2>${tr.experts}</h2><p>${lang==='fr'?'Une équipe multidisciplinaire présentée à partir des informations fournies.':'A multidisciplinary team presented from the information supplied.'}</p></div><div class="expert-grid">${experts.map(expertCard).join('')}</div></section>
  <section class="section"><div class="newsletter-strip"><div><span class="eyebrow">Newsletter</span><h2>${tr.newsletter}</h2><p>${lang==='fr'?'Recevez les publications approuvées de l’entreprise.':'Receive approved company updates and publications.'}</p></div><a class="cta" href="${pathFor('newsletter')}">${tr.newsletter}</a></div></section></main>`;
}
function expertCard(e){ const title=lang==='fr'?e.titleFr:e.titleEn; const bio=lang==='fr'?e.bioFr:e.bioEn; return `<article class="expert-card">${e.image?`<img src="${e.image}" width="600" height="750" loading="lazy" decoding="async" alt="Portrait of ${esc(e.name)}, ${esc(title)}">`:`<div class="expert-placeholder" aria-label="${esc(e.name)}">${esc(e.name.split(' ').map(x=>x[0]).join('').slice(0,3))}</div>`}<div class="expert-body"><h3>${esc(e.name)}</h3><p class="expert-title">${esc(title)}</p><p>${esc(bio)}</p><a class="text-link" href="${pathFor(`experts/${e.slug}`)}">${tr.readBio}</a></div></article>`; }

function servicesPage(){ return `<main id="main-content" class="page-shell">${hero(tr.services)}<section class="section"><div class="toggle" role="tablist"><button class="toggle-btn active" type="button" data-show="services">${tr.what}</button><button class="toggle-btn" type="button" data-show="industries">${tr.who}</button></div><div id="services" class="toggle-panel"><h2>${tr.what}</h2><div class="card-grid">${services.map(s=>card(lang==='fr'?s.fr:s.en,s.desc,`${pathFor('services-industries/services')}/${s.slug}`)).join('')}</div></div><div id="industries" class="toggle-panel" hidden><h2>${tr.who}</h2><div class="card-grid">${industries.map(i=>card(lang==='fr'?i.fr:i.en,lang==='fr'?'Secteur cible':'Target sector',`${pathFor('services-industries/industries')}/${i.slug}`)).join('')}</div></div></section></main>`; }
function genericPage(key){ const title=pages[key]?.[lang]||key; return `<main id="main-content" class="page-shell">${hero(title)}<section class="section"><div class="section-header"><h2>${esc(title)}</h2><p>${tr.legalReview}</p></div>${key==='projects'?`<div class="empty-state">${lang==='fr'?'Aucun projet vérifié n’est publié pour le moment.':'No verified projects are published at this time.'}</div>`:''}${key==='actuality'?`<div class="empty-state">${tr.emptyNews}</div>`:''}${key==='careers'?`<div class="empty-state"><p>${tr.noJobs}</p><a class="cta" href="${pathFor('careers/apply')}">${tr.spontaneous}</a></div>`:''}</section></main>`; }
function expertPage(slug){ const e=experts.find(x=>x.slug===slug); if(!e)return null; return `<main id="main-content" class="page-shell">${hero(e.name,e[lang==='fr'?'titleFr':'titleEn'])}<section class="section expert-detail"><div class="expert-detail-grid">${e.image?`<img src="${e.image}" width="600" height="750" loading="eager" alt="Portrait of ${esc(e.name)}, ${esc(e[lang==='fr'?'titleFr':'titleEn'])}">`:`<div class="expert-placeholder large">${esc(e.name.split(' ').map(x=>x[0]).join('').slice(0,3))}</div>`}<div><h2>${esc(e[lang==='fr'?'titleFr':'titleEn'])}</h2><p>${esc(e[lang==='fr'?'bioFr':'bioEn'])}</p><h3>${tr.what}</h3><ul>${(lang==='fr'?e.expertiseFr:e.expertiseEn).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><a class="cta" href="${pathFor('contact')}">${tr.talk}</a></div></div></section></main>`; }
function serviceDetail(slug){ const s=services.find(x=>x.slug===slug); if(!s)return null; const title=lang==='fr'?s.fr:s.en; return `<main id="main-content" class="page-shell">${hero(title,s.desc)}<section class="section"><h2>${esc(title)}</h2><p>${esc(s.desc)}</p><a class="cta" href="${pathFor('contact')}">${tr.advisory}</a></section></main>`; }
function industryDetail(slug){ const i=industries.find(x=>x.slug===slug); if(!i)return null; const title=lang==='fr'?i.fr:i.en; return `<main id="main-content" class="page-shell">${hero(title,lang==='fr'?'Secteur cible':'Target sector')}<section class="section"><h2>${esc(title)}</h2><p>${lang==='fr'?'Informations sectorielles détaillées publiées après validation de l’entreprise.':'Detailed sector information will be published after company validation.'}</p><a class="cta" href="${pathFor('contact')}">${tr.advisory}</a></section></main>`; }
function newsletter(){ return `<main id="main-content" class="page-shell">${hero(tr.newsletter)}<section class="section"><div class="form-card"><h2>${tr.newsletter}</h2><form id="newsletter-form" novalidate><label>${tr.email}<input name="email" type="email" required autocomplete="email"></label><label class="check"><input name="consent" type="checkbox" required> ${lang==='fr'?'J’accepte de recevoir les communications prévues par la newsletter et je reconnais la politique de confidentialité.':'I consent to receive the newsletter communications described and acknowledge the Privacy Policy.'}</label><button class="cta" type="submit">${tr.newsletter}</button><div class="form-status" role="status" aria-live="polite"></div></form></div></section></main>`; }
function contact(){ return `<main id="main-content" class="page-shell">${hero(tr.contact,tr.contactIntro)}<section class="section contact-layout"><div class="office-card"><h2>${tr.offices}</h2><ul class="office-list">${site.company.offices.map(o=>`<li>${esc(o[lang])}</li>`).join('')}</ul></div><div class="form-card"><form id="contact-form" novalidate><div class="form-grid"><label>${tr.fullName} *<input name="fullName" required autocomplete="name"></label><label>${tr.email} *<input name="email" type="email" required autocomplete="email"></label><label>${tr.phone} *<input name="phone" type="tel" required autocomplete="tel"></label><label>${tr.subject} *<input name="subject" required></label></div><label>${tr.message} *<textarea name="message" rows="7" required></textarea></label><div class="privacy-box"><label class="check"><input name="privacy" type="checkbox" required> ${lang==='fr'?'J’ai lu et j’accepte le traitement décrit dans la politique de confidentialité.':'I have read and acknowledge the processing described in the Privacy Policy.'}</label></div><div class="captcha-box"><div id="recaptcha-container"></div><p class="captcha-message" id="captcha-message">${tr.captchaUnavailable}</p></div><button class="cta" id="contact-submit" type="submit" disabled>${tr.send}</button><div class="form-status" role="status" aria-live="polite"></div></form></div></section></main>`; }
function apply(){ return `<main id="main-content" class="page-shell">${hero(tr.spontaneous)}<section class="section"><div class="form-card"><form id="application-form" enctype="multipart/form-data"><div class="form-grid"><label>${tr.fullName} *<input name="fullName" required></label><label>${tr.email} *<input name="email" type="email" required></label><label>${tr.phone}<input name="phone" type="tel"></label><label>Position *<input name="position" required></label></div><label>CV *<input name="cv" type="file" accept=".pdf,.docx" required></label><label>Cover letter<textarea name="coverLetter" rows="6"></textarea></label><label class="check"><input name="privacy" type="checkbox" required> ${lang==='fr'?'J’accepte la notice de confidentialité du recrutement.':'I acknowledge the Recruitment Privacy Notice.'}</label><label class="check"><input name="futureConsent" type="checkbox"> ${lang==='fr'?'Je consens séparément à la conservation pour de futures opportunités.':'I separately consent to retention for future opportunities.'}</label><button class="cta" type="submit">${lang==='fr'?'Envoyer la candidature':'Submit application'}</button><div class="form-status" role="status" aria-live="polite"></div></form></div></section></main>`; }
function legalPage(key){ const title=legalPages[key]?.[lang]||key; return `<main id="main-content" class="page-shell">${hero(title)}<section class="section legal-copy"><p>${tr.legalReview}</p><h2>${title}</h2><p>${lang==='fr'?'Cette page décrit les principes applicables au traitement, à la sécurité, au consentement et à l’accessibilité du site, sous réserve de validation juridique.':'This page describes the principles applicable to processing, security, consent and accessibility for the website, subject to legal review.'}</p><h3>${lang==='fr'?'Données et finalités':'Data and purposes'}</h3><p>${lang==='fr'?'Les données sont collectées uniquement lorsque nécessaires à une demande précise, à une candidature ou à une inscription volontaire à la newsletter.':'Data is collected only when necessary for a defined inquiry, application or voluntary newsletter subscription.'}</p><h3>${lang==='fr'?'Droits et demandes':'Rights and requests'}</h3><p>${tr.officialPending}</p></section></main>`; }
function adminPage(){return `<main id="main-content" class="page-shell"><section class="section"><div class="form-card" id="admin-app"><h1>Admin</h1><p>Authorized content management area.</p><form id="admin-login"><label>Email<input name="email" type="email" required autocomplete="username"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button class="cta" type="submit">Sign in</button><div class="form-status" role="status" aria-live="polite"></div></form></div></section></main>`}
async function bindAdmin(){const root=document.querySelector('#admin-app');if(!root)return;const me=await fetch('/api/admin/me').then(r=>r.ok?r.json():null).catch(()=>null);if(!me)return;root.innerHTML=`<h1>Admin dashboard</h1><p>Signed in as ${esc(me.email)} (${esc(me.role)}).</p><div class="card-grid"><article class="card"><h3>Inquiries</h3><div id="admin-inquiries">Loading…</div></article><article class="card"><h3>Applications</h3><div id="admin-applications">Loading…</div></article><article class="card"><h3>Audit log</h3><div id="admin-audit">Loading…</div></article></div><button class="cta" id="admin-logout" type="button">Sign out</button>`;const [iq,ap,au]=await Promise.all([fetch('/api/admin/inquiries').then(r=>r.ok?r.json():[]),fetch('/api/admin/applications').then(r=>r.ok?r.json():[]),fetch('/api/admin/audit').then(r=>r.ok?r.json():[])]);document.querySelector('#admin-inquiries').textContent=`${iq.length} record(s)`;document.querySelector('#admin-applications').textContent=`${ap.length} application(s)`;document.querySelector('#admin-audit').textContent=`${au.length} audit event(s)`;document.querySelector('#admin-logout').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()}}
function bindAdminLogin(){const form=document.querySelector('#admin-login');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const j=await r.json();if(r.ok)location.href='/admin';else status.textContent=j.message||'Login failed.'})}

function setMetadata(){const names={about:tr.about,services:tr.services,projects:tr.projects,insights:tr.insights,actuality:tr.actuality,sustainability:tr.sustainability,experts:tr.experts,careers:tr.careers,contact:tr.contact,newsletter:tr.newsletter};let title=tr.home;if(path.includes('/services-industries'))title=tr.services;else{for(const [k,v] of Object.entries(names)){if(path.endsWith('/'+k)||path.includes('/'+k+'/')){title=v;break}}}document.title=`${title} | Africa Power Advisory Holding`;const desc=document.querySelector('meta[name="description"]');if(desc)desc.content=path.includes('/contact')?tr.contactIntro:tr.hero;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=location.origin+pathFor(path.replace(/^\/(fr|en)/,'').replace(/\/$/,'')||'');for(const rel of document.querySelectorAll('link[data-hreflang]'))rel.remove();for(const l of ['fr','en']){const link=document.createElement('link');link.rel='alternate';link.hreflang=l;link.href=location.origin+`/${l}/`;link.dataset.hreflang='true';document.head.appendChild(link)}}

function render(){
  let body;
  if(isAdmin) body=adminPage();
  else if(isRoot) body=home();
  else if(path.endsWith('/services-industries') || path.endsWith('/services-et-secteurs')) body=servicesPage();
  else if(path.includes('/services-industries/services/')) body=serviceDetail(path.split('/').pop());
  else if(path.includes('/services-industries/industries/')) body=industryDetail(path.split('/').pop());
  else if(path.includes('/experts/')) body=expertPage(path.split('/').pop()) || genericPage('experts');
  else if(path.endsWith('/newsletter')) body=newsletter();
  else if(path.endsWith('/contact')) body=contact();
  else if(path.endsWith('/careers/apply')) body=apply();
  else if(path.includes('/legal/')) body=legalPage(path.split('/').pop());
  else { const key=Object.keys(pages).find(k=>path.endsWith(`/${k}`) || (k==='about'&&path.endsWith('/a-propos')) || (k==='projects'&&path.endsWith('/projets')) || (k==='insights'&&path.endsWith('/analyses')) || (k==='actuality'&&path.endsWith('/actualites')) || (k==='sustainability'&&path.endsWith('/durabilite')) || (k==='careers'&&path.endsWith('/carrieres'))); body=key?genericPage(key):`<main id="main-content" class="not-found"><div class="not-found-inner"><div class="code">404</div><h1>${tr.error404}</h1><p>${tr.error404Text}</p><a class="cta" href="${prefix}/">${tr.homeReturn}</a></div></main>`; }
  document.querySelector('#app').innerHTML=header()+body+footer()+dialog();
  document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear());
  setMetadata();
  bind();
  if(isAdmin){bindAdminLogin();bindAdmin();}
}
function bind(){
  const headerEl=document.querySelector('#site-header'); addEventListener('scroll',()=>headerEl?.classList.toggle('scrolled',scrollY>10),{passive:true});
  const panel=document.querySelector('#mobile-panel'),open=document.querySelector('#menu-open'),close=document.querySelector('#menu-close'); let focus;
  const closeMenu=()=>{panel?.setAttribute('data-open','false');panel?.setAttribute('aria-hidden','true');open?.setAttribute('aria-expanded','false');document.body.style.overflow='';focus?.focus()};
  open?.addEventListener('click',()=>{focus=document.activeElement;panel.setAttribute('data-open','true');panel.setAttribute('aria-hidden','false');open.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';panel.querySelector('a,button')?.focus()}); close?.addEventListener('click',closeMenu); panel?.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()}); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()},{once:true});
  const dialogEl=document.querySelector('#site-search'), input=document.querySelector('#search-input'), results=document.querySelector('#search-results');
  const openSearch=()=>{dialogEl?.showModal();setTimeout(()=>input?.focus(),20)}; document.querySelector('#search-open')?.addEventListener('click',openSearch); document.querySelector('#mobile-search-open')?.addEventListener('click',()=>{closeMenu();openSearch()}); document.querySelector('#search-close')?.addEventListener('click',()=>dialogEl.close());
  input?.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='';return;}const found=siteIndex.filter(x=>`${x.title} ${x.desc}`.toLowerCase().includes(q));results.innerHTML=found.length?found.map(x=>`<a class="search-result" href="${x.url}"><b>${esc(x.title)}</b><br><span>${esc(x.desc)}</span></a>`).join(''):`<p role="status">${tr.searchNo}</p>`});
  const setTheme=theme=>{document.documentElement.dataset.theme=theme;localStorage.setItem('apah-theme',theme);document.querySelectorAll('#theme-toggle,#mobile-theme-toggle').forEach(b=>b.textContent=theme==='dark'?tr.light:tr.dark)};setTheme(localStorage.getItem('apah-theme')||'light');document.querySelectorAll('#theme-toggle,#mobile-theme-toggle').forEach(b=>b.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')));
  document.querySelectorAll('.toggle-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.toggle-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.toggle-panel').forEach(x=>x.hidden=true);btn.classList.add('active');document.getElementById(btn.dataset.show).hidden=false}));
  bindContact(); bindNewsletter(); bindApplication();
}
async function bindContact(){const form=document.querySelector('#contact-form');if(!form)return;const submit=form.querySelector('#contact-submit');const status=form.querySelector('.form-status');let config={};try{config=await fetch('/api/config').then(r=>r.json())}catch{}if(!config.recaptchaSiteKey){status.textContent=tr.captchaUnavailable;return;}window.onAPAHRecaptcha=token=>{form.dataset.captcha=token;submit.disabled=false;document.querySelector('#captcha-message').textContent='';};window.APAHRecaptchaLoaded=()=>window.grecaptcha.render('recaptcha-container',{sitekey:config.recaptchaSiteKey,callback:'onAPAHRecaptcha'});const script=document.createElement('script');script.src='https://www.google.com/recaptcha/api.js?onload=APAHRecaptchaLoaded&render=explicit';script.async=true;script.defer=true;document.head.appendChild(script);form.addEventListener('submit',async e=>{e.preventDefault();if(!form.dataset.captcha){status.textContent=tr.recaptcha;return;}submit.disabled=true;const data=Object.fromEntries(new FormData(form));data.captchaToken=form.dataset.captcha;data.language=lang;try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();status.textContent=r.ok?tr.success:(j.message||tr.error);if(r.ok){form.reset();form.dataset.captcha='';}}catch{status.textContent=tr.error;}submit.disabled=true;});}
function bindNewsletter(){const form=document.querySelector('#newsletter-form');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');const data=Object.fromEntries(new FormData(form));const r=await fetch('/api/newsletter/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,language:lang})});const j=await r.json();status.textContent=r.ok?(lang==='fr'?'Vérifiez votre boîte de réception et confirmez votre abonnement.':'Please check your inbox and confirm your subscription.'):(j.message||tr.error);if(r.ok)form.reset();});}
function bindApplication(){const form=document.querySelector('#application-form');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');const data=new FormData(form);data.append('language',lang);const r=await fetch('/api/applications',{method:'POST',body:data});const j=await r.json();status.textContent=r.ok?(lang==='fr'?'Votre candidature a été reçue.':'Your application has been received.'):(j.message||tr.error);if(r.ok)form.reset();});}

render();
